# -*- coding: utf-8 -*-
"""Test_CITMOS.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kuvUb7KNfwekm8bqpfF6mTUUHOSG0oZP

## 1.Importar Librerías
"""

import pandas as pd
import numpy as np
import re
import warnings
warnings.filterwarnings("ignore")

"""## 2.Cargar Datos"""

## CARGAR DATOS EN EXCEL
##----------------------

bikes   = pd.read_excel('/content/Bikes.xlsx')
b_shops = pd.read_excel('/content/bikeshops.xlsx')
orders  = pd.read_excel('/content/orderlines.xlsx')

# Tabla bicicletas
bikes.head()

# Tabla de tiendas
b_shops.head()

# Tabla de ordenes de compra
orders.head()

"""## 3. Fusionar Tablas"""

# Fusión de tablas en una sola
df = orders.merge(b_shops, left_on='order.id', right_on='bikeshop.id')
df = df.merge(bikes, left_on='product.id', right_on='bike.id')

# Verificar
df.head()

## Crear categorías
df['description'].unique()

## Crear columna con categorías y verificar
df['tipo'] = df['description'].str.split(' - ').str[0]
df['tipo'].unique()

## Crear y calcular revenue
cantidad = df['quantity']
precio   = df['price']

df['revenue'] = cantidad * precio

# Nuedo dataframe con variables específicas + categoría(tipo) y revenue

df_2 = df[['order.date', 'model', 'description', 'quantity', 'price', 'tipo', 'revenue']]
df_2

"""## 4.Filtrar Modelos y Estados"""

# Crear nueva columna de estados

df_2['location'] = df['location']
df_2['state'] = df_2['location'].str.split(',').str[1]
df_2

## Crear un filtro solo con los modelos super six

patron = r'Supersix.*'
supersix_models = df_2[df_2['model'].str.contains(patron)]

supersix_models

"""## 5.Clasificar Cuantiles y Estado"""

## Crear clasificación con los cuantiles altos, medios y bajos en una nueva columna
## Solo para modelos supersix en los estados de Florida

cuantiles = pd.qcut(
    df['revenue'],
    q=[0, 0.25, 0.75, 1],
    labels=['low', 'medium', 'high']
    )

supersix_models['revenue_quantiles'] = cuantiles
supersix_models

## Crear Filtro para los Edos de FL

florida = supersix_models[supersix_models['state']==' FL']
florida